#pragma config(Motor,  port3,           Intake1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RightMotor1,   tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           LeftMotor1,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port6,           LeftMotor2,    tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port7,           Intake2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RightMotor2,   tmotorVex393_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
			while(1)
			{
				//Wheels
				motor[RightMotor1] = vexRT(ch2);
				motor[LeftMotor1] = vexRT(ch3);
				motor[RightMotor2] = vexRT(ch2);
				motor[LeftMotor2] = vexRT(ch3);
				//Intake
				if (vexRT[Btn6D] == 1)
				{
					motor[Intake1] = 127;
					motor[Intake2] = 127;

				}

				else if (vexRT[Btn6U] == 1)
				{
					motor[Intake1] = -127;
					motor[Intake2] = -127;
				}
				else
				{
					motor[Intake1] = 0;
					motor[Intake2] = 0;
				}
			}



}
