#pragma config(Motor,  port2,           RampR,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           DriveR1,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           DriveR2,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           IntakeL,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           IntakeR,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           DriveL1,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           DriveL2,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RampL,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
  // .....................................................................................
  // Insert user code here.
  // .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
	  // This is the main execution loop for the user control program. Each time through the loop
	  // your program should update motor + servo values based on feedback from the joysticks.

		//Wheels
		motor[DriveR1] = vexRT(Ch2);
		motor[DriveL1] = vexRT(Ch3);
		motor[DriveR2] = vexRT(Ch2);
		motor[DriveL2] = vexRT(Ch3);

		//Intake
		// Spin the intake motors forward
		if (vexRT[Btn6D] == 1)
		{
			motor[IntakeL] = 127;
			motor[IntakeR] = 127;

		}
		// Spin the intake motors backward
		else if (vexRT[Btn6U] == 1)
		{
			motor[IntakeL] = -127;
			motor[IntakeR] = -127;
		}
		// Stop the intake motors.
		else
		{
			motor[IntakeL] = 0;
			motor[IntakeR] = 0;
		}

		// Ramp motors?
		// Run both in one direction
		if (vexRT[Btn7U] == 1)
		{
			motor[RampR] = 127;
			motor[RampL] = 127;
		}
		// Run both in the other direction
		else if (vexRT[Btn7D] == 1)
		{
			motor[RampR] = -127;
			motor[RampL] = -127;
		}
		// Stop motors
		else
		{
			motor[RampR] = 0;
			motor[RampL] = 0;
		}
	}
}
